// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dist_wtbinary
Rcpp::NumericMatrix dist_wtbinary(Rcpp::NumericMatrix ww);
RcppExport SEXP _survClust_dist_wtbinary(SEXP wwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type ww(wwSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_wtbinary(ww));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _survClust_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_survClust_dist_wtbinary", (DL_FUNC) &_survClust_dist_wtbinary, 1},
    {"_survClust_rcpp_hello_world", (DL_FUNC) &_survClust_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_survClust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
