# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_wtbinary <- function(ww) {
    .Call(`_survClust_dist_wtbinary`, ww)
}

rcpp_hello_world <- function() {
    .Call(`_survClust_rcpp_hello_world`)
}

