# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Calculates distance on weighted matrix for binary(mutation) datatype. Called internally by getDist, See type in getDist. 
#'
#'@param ww weighted data matrix.
#'@export
NULL

dist_wtbinary <- function(ww) {
    .Call('_survClust_dist_wtbinary', PACKAGE = 'survClust', ww)
}

